### ISSUE TITLE
Update auto copy of new md files in docs

### ISSUE THREAD

**Issue by AlexandreGazagnes** [AlexandreGazagnes/awdible#33]
## Context

In the ```pre-commit.yaml```, we have 

```yaml
# docs
-   repo: local
    hooks:
    -   id: update_docs
        language: script
        name: update_docs
        entry: .utils/docs.sh
        stage: [commit]
        
```

This script is used to update the ```README.md``` file to the ```docs/docs/index.md``` file.

## Improvement

Now we have ```CONTRIBUTING.md```, ```SECURITY.md```, and ```CODE_OF_CONDUCT.md```.
We should apply the same logic to these files.

- [x] Update ```.utils/docs.sh``` to handle these files
- [x] Update ```pre-commit.yaml``` to handle these files
- [x] Update the ```docs/mkdocs.yml``` to handle these files
